---
- name: Testing andrewrothstein.etcd
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
- name: Testing 'etcd --version'
  ansible.builtin.import_playbook: test-exe.yml
  vars:
    exe: etcd
    dash_version: --version
- name: Testing 'etcdctl version'
  ansible.builtin.import_playbook: test-exe.yml
  vars:
    exe: etcdctl
    dash_version: version
- name: Testing 'etcdutl version'
  ansible.builtin.import_playbook: test-exe.yml
  vars:
    exe: etcdutl
    dash_version: version
