---
- name: Testing '{{ exe }} {{ dash_version }}'
  hosts: all
  tasks:
    - name: Executing '{{ exe }} {{ dash_version }}'
      ansible.builtin.command: '{{ exe }} {{ dash_version }}'
      changed_when: false
      register: exe_output
    - name: Output from '{{ exe }} {{ dash_version }}'
      ansible.builtin.debug:
        msg: '{{ exe_output.stdout }}'
