---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/etcd --version
      register: etcd_test_output
    - debug:
        msg: '{{ etcd_test_output.stdout }}'
    - command: /usr/local/bin/etcdctl version
      register: etcdctl_test_output
    - debug:
        msg: '{{ etcdctl_test_output.stdout }}'
