---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
- import_playbook: test-exe.yml
  vars:
    exe: /usr/local/bin/etcd
    dash_version: --version
- import_playbook: test-exe.yml
  vars:
    exe: /usr/local/bin/etcdctl
    dash_version: version
- import_playbook: test-exe.yml
  vars:
    exe: /usr/local/bin/etcdutl
    dash_version: version
